<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EmuShelf.Core\EmuShelf.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    <PackageReference Include="Shamisen.Codecs.Flac" Version="0.1.0-alpha.0.8.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EmuShelf.Infrastructure.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
